<template>
  <div class="wrapper" ref="wrapper">
    <!--<ul class="content">
      <li>fenl1</li>
      <li>fenl2</li>
      <li>fenl3</li>
      <li>fenl4</li>
      <li>fenl5</li>
      <li>fenl6</li>
      <li>fenl7</li>
      <li>fenl8</li>
      <li>fenl9</li>
      <li>fenl10</li>
      <li>fenl11</li>
      <li>fenl12</li>
      <li>fenl13</li>
      <li>fenl14</li>
      <li>fenl15</li>
      <li>fenl16</li>
      <li>fenl17</li>
      <li>fenl18</li>
      <li>fenl19</li>
      <li>fenl20</li>
      <li>fenl21</li>
      <li>fenl22</li>
      <li>fenl23</li>
      <li>fenl24</li>
      <li>fenl25</li>
      <li>fenl26</li>
      <li>fenl27</li>
      <li>fenl28</li>
      <li>fenl29</li>
      <li>fenl30</li>
      <li>fenl31</li>
      <li>fenl32</li>
      <li>fenl33</li>
      <li>fenl34</li>
      <li>fenl35</li>
      <li>fenl36</li>
      <li>fenl37</li>
      <li>fenl38</li>
      <li>fenl39</li>
      <li>fenl40</li>
      <li>fenl41</li>
      <li>fenl42</li>
      <li>fenl43</li>
      <li>fenl44</li>
      <li>fenl45</li>
      <li>fenl46</li>
      <li>fenl47</li>
      <li>fenl48</li>
      <li>fenl49</li>
      <li>fenl50</li>
      <li>fenl51</li>
      <li>fenl52</li>
      <li>fenl53</li>
      <li>fenl54</li>
      <li>fenl55</li>
      <li>fenl56</li>
      <li>fenl57</li>
      <li>fenl58</li>
      <li>fenl59</li>
      <li>fenl60</li>
      <li>fenl61</li>
      <li>fenl62</li>
      <li>fenl63</li>
      <li>fenl64</li>
      <li>fenl65</li>
      <li>fenl66</li>
      <li>fenl67</li>
      <li>fenl68</li>
      <li>fenl69</li>
      <li>fenl70</li>
      <li>fenl71</li>
      <li>fenl72</li>
      <li>fenl73</li>
      <li>fenl74</li>
      <li>fenl75</li>
      <li>fenl76</li>
      <li>fenl77</li>
      <li>fenl78</li>
      <li>fenl79</li>
      <li>fenl80</li>
      <li>fenl81</li>
      <li>fenl82</li>
      <li>fenl83</li>
      <li>fenl84</li>
      <li>fenl85</li>
      <li>fenl86</li>
      <li>fenl87</li>
      <li>fenl88</li>
      <li>fenl89</li>
      <li>fenl90</li>
      <li>fenl91</li>
      <li>fenl92</li>
      <li>fenl93</li>
      <li>fenl94</li>
      <li>fenl95</li>
      <li>fenl96</li>
      <li>fenl97</li>
      <li>fenl98</li>
      <li>fenl99</li>
      <li>fenl100</li>
      <li>fenl101</li>
      <li>fenl102</li>
      <li>fenl103</li>
      <li>fenl104</li>
      <li>fenl105</li>
      <li>fenl106</li>
      <li>fenl107</li>
      <li>fenl108</li>
      <li>fenl109</li>
      <li>fenl110</li>
      <li>fenl111</li>
      <li>fenl112</li>
      <li>fenl113</li>
      <li>fenl114</li>
      <li>fenl115</li>
      <li>fenl116</li>
      <li>fenl117</li>
      <li>fenl118</li>
      <li>fenl119</li>
      <li>fenl120</li>
      <li>fenl121</li>
      <li>fenl122</li>
      <li>fenl123</li>
      <li>fenl124</li>
      <li>fenl125</li>
      <li>fenl126</li>
      <li>fenl127</li>
      <li>fenl128</li>
      <li>fenl129</li>
      <li>fenl130</li>
      <li>fenl131</li>
      <li>fenl132</li>
      <li>fenl133</li>
      <li>fenl134</li>
      <li>fenl135</li>
      <li>fenl136</li>
      <li>fenl137</li>
      <li>fenl138</li>
      <li>fenl139</li>
      <li>fenl140</li>
      <li>fenl141</li>
      <li>fenl142</li>
      <li>fenl143</li>
      <li>fenl144</li>
      <li>fenl145</li>
      <li>fenl146</li>
      <li>fenl147</li>
      <li>fenl148</li>
      <li>fenl149</li>
      <li>fenl150</li>
      <li>fenl151</li>
      <li>fenl152</li>
      <li>fenl153</li>
      <li>fenl154</li>
      <li>fenl155</li>
      <li>fenl156</li>
      <li>fenl157</li>
      <li>fenl158</li>
      <li>fenl159</li>
      <li>fenl160</li>
      <li>fenl161</li>
      <li>fenl162</li>
      <li>fenl163</li>
      <li>fenl164</li>
      <li>fenl165</li>
      <li>fenl166</li>
      <li>fenl167</li>
      <li>fenl168</li>
      <li>fenl169</li>
      <li>fenl170</li>
      <li>fenl171</li>
      <li>fenl172</li>
      <li>fenl173</li>
      <li>fenl174</li>
      <li>fenl175</li>
      <li>fenl176</li>
      <li>fenl177</li>
      <li>fenl178</li>
      <li>fenl179</li>
      <li>fenl180</li>
      <li>fenl181</li>
      <li>fenl182</li>
      <li>fenl183</li>
      <li>fenl184</li>
      <li>fenl185</li>
      <li>fenl186</li>
      <li>fenl187</li>
      <li>fenl188</li>
      <li>fenl189</li>
      <li>fenl190</li>
      <li>fenl191</li>
      <li>fenl192</li>
      <li>fenl193</li>
      <li>fenl194</li>
      <li>fenl195</li>
      <li>fenl196</li>
      <li>fenl197</li>
      <li>fenl198</li>
      <li>fenl199</li>
      <li>fenl200</li>
    </ul>-->
  </div>
</template>

<script>
  import BScroll  from 'better-scroll'
    export default {
        name: "Category",
      data(){
          return {
            scroll:null
          }
      },
      mounted(){
         // new BS('.wrapper',{});
        //this.scroll=  new BScroll (document.querySelector('.wrapper'));
       /* this.scroll=  new BScroll (this.$refs.wrapper,{
          probeType:3,
          pullUpLoad:true
        });
        this.scroll.on('scroll',(position)=>{
          console.log(position);
        })
        this.scroll.on('pullingUp',(position)=>{
          console.log('拉扯到你最爱');  })
*/
      }

    }
</script>

<style scoped>
.wrapper{
  height:150px;
  background-color: red;
}
</style>
